from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Mapping


class ErrorCode(str, Enum):
    ABSOLUTE_BUDGET_FORBIDDEN = "ABSOLUTE_BUDGET_FORBIDDEN"
    FLOAT_RATE_FORBIDDEN = "FLOAT_RATE_FORBIDDEN"
    RATE_NOT_INTEGRAL = "RATE_NOT_INTEGRAL"
    DENOMINATOR_IDENTITY_MISMATCH = "DENOMINATOR_IDENTITY_MISMATCH"
    IDENTITY_DIGEST_MISMATCH = "IDENTITY_DIGEST_MISMATCH"
    T_POOL_ROLE_MISMATCH = "T_POOL_ROLE_MISMATCH"
    R1_UNIVERSE_NOT_GLOBAL = "R1_UNIVERSE_NOT_GLOBAL"
    R2_OVERLAPS_T = "R2_OVERLAPS_T"
    R2_QUOTA_INFEASIBLE = "R2_QUOTA_INFEASIBLE"
    TERMINAL_FIELD_ACCESS_FORBIDDEN = "TERMINAL_FIELD_ACCESS_FORBIDDEN"
    SCHEDULE_EXPOSURE_MISMATCH = "SCHEDULE_EXPOSURE_MISMATCH"
    SCHEDULE_MULTIPLICITY_MISMATCH = "SCHEDULE_MULTIPLICITY_MISMATCH"
    BASE_ORDER_MISMATCH = "BASE_ORDER_MISMATCH"
    BASE_AUGMENTATION_MISMATCH = "BASE_AUGMENTATION_MISMATCH"
    BASE_STEP_COUNT_MISMATCH = "BASE_STEP_COUNT_MISMATCH"
    REPLAY_MICROBATCH_CAP_EXCEEDED = "REPLAY_MICROBATCH_CAP_EXCEEDED"
    REPLAY_ADDED_OPTIMIZER_STEP = "REPLAY_ADDED_OPTIMIZER_STEP"
    OPTIMIZER_STEP_SKIPPED = "OPTIMIZER_STEP_SKIPPED"
    BN_BUFFER_NOT_RESTORED = "BN_BUFFER_NOT_RESTORED"
    RNG_NOT_RESTORED = "RNG_NOT_RESTORED"
    PARENT_CHECKPOINT_INCOMPLETE = "PARENT_CHECKPOINT_INCOMPLETE"
    PARENT_SHA_MISMATCH = "PARENT_SHA_MISMATCH"
    BRANCH_LINEAGE_MISMATCH = "BRANCH_LINEAGE_MISMATCH"
    CHILD_MUTATED_PARENT = "CHILD_MUTATED_PARENT"
    LOGICAL_ARTIFACT_IDENTITY_MISMATCH = "LOGICAL_ARTIFACT_IDENTITY_MISMATCH"
    BEST_PT_FORBIDDEN = "BEST_PT_FORBIDDEN"
    VAL_OP_SELECTION_FORBIDDEN = "VAL_OP_SELECTION_FORBIDDEN"
    TEST_ACCESS_FORBIDDEN = "TEST_ACCESS_FORBIDDEN"
    BLOCKED_BY_VAL_TARGET = "BLOCKED_BY_VAL_TARGET"
    WEIGHTED_QRAD_FORBIDDEN = "WEIGHTED_QRAD_FORBIDDEN"
    CANDIDATE_SIGNAL_AS_UTILITY_FORBIDDEN = "CANDIDATE_SIGNAL_AS_UTILITY_FORBIDDEN"
    DISTRIBUTED_MODE_NOT_SUPPORTED_IN_V4_PHASE1 = "DISTRIBUTED_MODE_NOT_SUPPORTED_IN_V4_PHASE1"
    OOM_FIXED_CONTRACT_ABORT = "OOM_FIXED_CONTRACT_ABORT"
    DISK_SPACE_PRECHECK_FAILED = "DISK_SPACE_PRECHECK_FAILED"
    ATOMIC_TRANSACTION_INCOMPLETE = "ATOMIC_TRANSACTION_INCOMPLETE"
    RESUME_GENERATION_MISMATCH = "RESUME_GENERATION_MISMATCH"
    SYNTHETIC_RESULT_MISLABELLED = "SYNTHETIC_RESULT_MISLABELLED"
    FORMAL_RELEASE_NOT_AUTHORIZED = "FORMAL_RELEASE_NOT_AUTHORIZED"
    FORMAL_EXECUTION_TOKEN_INVALID = "FORMAL_EXECUTION_TOKEN_INVALID"
    FORMAL_EXECUTION_TOKEN_ALREADY_CLAIMED = "FORMAL_EXECUTION_TOKEN_ALREADY_CLAIMED"
    LEGACY_ASSIGNMENT_REUSE_FORBIDDEN = "LEGACY_ASSIGNMENT_REUSE_FORBIDDEN"
    DATASET_CONTENT_LEDGER_REQUIRED = "DATASET_CONTENT_LEDGER_REQUIRED"
    DATASET_CONTENT_MISMATCH = "DATASET_CONTENT_MISMATCH"
    RUNBOOK_IDENTITY_MISMATCH = "RUNBOOK_IDENTITY_MISMATCH"
    RUN_INTENT_NOT_ACKNOWLEDGED = "RUN_INTENT_NOT_ACKNOWLEDGED"

    # Additional stable implementation codes used by v4 validators.
    SCHEMA_VALIDATION_FAILED = "SCHEMA_VALIDATION_FAILED"
    ASSET_VALIDATION_FAILED = "ASSET_VALIDATION_FAILED"
    DUPLICATE_IDENTITY = "DUPLICATE_IDENTITY"
    IDENTITY_NOT_IN_BASE = "IDENTITY_NOT_IN_BASE"
    CHECKPOINT_EPOCH_FORBIDDEN = "CHECKPOINT_EPOCH_FORBIDDEN"
    PREDICTION_IDENTITY_MISMATCH = "PREDICTION_IDENTITY_MISMATCH"
    FRONTIER_INVALID = "FRONTIER_INVALID"
    STATISTICS_PAIR_MISSING = "STATISTICS_PAIR_MISSING"
    TELEMETRY_UNAVAILABLE = "TELEMETRY_UNAVAILABLE"
    COLUMNAR_ENGINE_UNAVAILABLE = "COLUMNAR_ENGINE_UNAVAILABLE"
    SOURCE_TREE_MISMATCH = "SOURCE_TREE_MISMATCH"
    FORMAL_SEEDS_BLOCKED_UNTIL_RELEASE = "FORMAL_SEEDS_BLOCKED_UNTIL_RELEASE"
    CURRENT_LOSS_HELD = "CURRENT_LOSS_HELD"
    SHORT_BRANCH_DISABLED = "SHORT_BRANCH_DISABLED"
    SELECTOR_TRAINING_FORBIDDEN = "SELECTOR_TRAINING_FORBIDDEN"
    INVALID_EXECUTION_MODE = "INVALID_EXECUTION_MODE"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    SEED_REGISTRY_INVALID = "SEED_REGISTRY_INVALID"
    ARTIFACT_VALIDATION_FAILED = "ARTIFACT_VALIDATION_FAILED"
    UPSTREAM_BINDING_FAILED = "UPSTREAM_BINDING_FAILED"
    CONFIGURATION_MISMATCH = "CONFIGURATION_MISMATCH"
    CLOSEOUT_NOT_VALIDATED = "CLOSEOUT_NOT_VALIDATED"


@dataclass(eq=False)
class SctsrError(RuntimeError):
    code: ErrorCode
    message: str
    failing_field: str | None = None
    observed: Any = None
    expected: Any = None
    artifact_path: str | None = None
    run_id: str | None = None
    arm_id: str | None = None
    seed: int | None = None
    epoch: int | None = None
    recoverable: bool = False
    required_action: str | None = None
    details: Mapping[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        RuntimeError.__init__(self, f"{self.code.value}: {self.message}")

    def to_dict(self) -> dict[str, Any]:
        return {
            "schema_version": "stage1.sctsr.error.v1",
            "code": self.code.value,
            "message": self.message,
            "failing_field": self.failing_field,
            "observed": self.observed,
            "expected": self.expected,
            "artifact_path": self.artifact_path,
            "run_id": self.run_id,
            "arm_id": self.arm_id,
            "seed": self.seed,
            "epoch": self.epoch,
            "recoverable": self.recoverable,
            "required_action": self.required_action,
            "details": dict(self.details),
        }
