"""Manually reviewed primary papers for the dynamic replay campaign.

The records here are deliberately small, explicit, and reviewable.  High-recall
metadata discovery lives in ``campaign_literature_registry``; this module is the
curated mechanism set for which the primary paper's method, experiments, and
scope or limitations were inspected.
"""

from __future__ import annotations

from dataclasses import dataclass


VERIFIED_AT = "2026-08-07"


@dataclass(frozen=True)
class DeepPaper:
    evidence_id: str
    title: str
    authors: str
    year: int
    venue: str
    primary_url: str
    doi: str
    topic: str
    direction_id: str
    method_family: str
    measured_quantity: str
    selection_unit: str
    training_stage_dependency: str
    distinguishes_beneficial_harmful: str
    required_fields: str
    stage1_testability: str
    stage1_implication: str
    method_summary: str
    claim_boundary: str
    evidence_relation: str
    abstract: str


def _record(paper: DeepPaper) -> dict[str, object]:
    return {
        "evidence_id": paper.evidence_id,
        "title": paper.title,
        "authors": paper.authors,
        "year": paper.year,
        "venue": paper.venue,
        "primary_url": paper.primary_url,
        "doi": paper.doi,
        "topic": paper.topic,
        "direction_id": paper.direction_id,
        "screening_depth": "DEEP_READ",
        "reading_basis": "PRIMARY_PAPER_METHOD_EXPERIMENTS_AND_SCOPE",
        "sections_checked": "ABSTRACT;METHOD;EXPERIMENTS;LIMITATIONS_OR_SCOPE_BOUNDARY",
        "method_family": paper.method_family,
        "measured_quantity": paper.measured_quantity,
        "selection_unit": paper.selection_unit,
        "training_stage_dependency": paper.training_stage_dependency,
        "distinguishes_beneficial_harmful": paper.distinguishes_beneficial_harmful,
        "required_fields": paper.required_fields,
        "stage1_testability": paper.stage1_testability,
        "stage1_implication": paper.stage1_implication,
        "method_summary": paper.method_summary,
        "claim_boundary": paper.claim_boundary,
        "evidence_relation": paper.evidence_relation,
        "primary_source_verified": True,
        "verified_at": VERIFIED_AT,
        "abstract": paper.abstract,
    }


_PAPERS = (
    DeepPaper(
        "DEEP_BAYESIAN_TDA_2023",
        "A Bayesian Approach To Analysing Training Data Attribution In Deep Learning",
        "Elisa Nguyen; Minjoon Seo; Seong Joon Oh",
        2023,
        "NeurIPS 2023",
        "https://proceedings.neurips.cc/paper_files/paper/2023/hash/ca774047bc3b46cc81e53ead34cd5d5a-Abstract-Conference.html",
        "10.52202/075280-2803",
        "TRAINING_RANDOMNESS",
        "D1_CONDITIONAL_VALUE",
        "Bayesian training-data attribution",
        "distribution of attribution over initialization and SGD batches",
        "training-test sample pair across model draws",
        "YES_ACROSS_RUNS",
        "YES_AS_A_DISTRIBUTION",
        "paired_seeds;batch_order;per_run_attribution_or_outcome",
        "DIRECT_DESIGN_GUIDANCE",
        "Treat the 23 same-selection seed reversals as a distributional effect, not ranking noise to average away.",
        "Treats learned models and attribution estimates as random variables and tests whether sample influence survives initialization and mini-batch noise.",
        "The paper warns that noise-independent influential pairs are rare; it does not provide a cheap scalar ranking for Stage1.",
        "SUPPORTS",
        "Individual attribution can be overshadowed by initialization and SGD batch composition.",
    ),
    DeepPaper(
        "DEEP_DISTRIBUTIONAL_TDA_2025",
        "Distributional Training Data Attribution: What do Influence Functions Sample?",
        "Bruno Kacper Mlodozeniec; Isaac Reid; Sam Power; David Krueger; Murat A. Erdogdu; Richard E. Turner; Roger Baker Grosse",
        2025,
        "NeurIPS 2025",
        "https://proceedings.neurips.cc/paper_files/paper/2025/hash/0e8909cae8248c98279f6cd82074aa6d-Abstract-Conference.html",
        "",
        "TRAINING_RANDOMNESS",
        "D1_CONDITIONAL_VALUE",
        "distributional training-data attribution",
        "change in the distribution of model outputs over training runs",
        "sample or subset across random training runs",
        "YES_ACROSS_RUNS",
        "YES_AS_A_DISTRIBUTION",
        "multi_seed_outputs;paired_dataset_perturbations;raw_predictions",
        "DIRECT_CONCEPTUAL_TARGET",
        "Estimate arm effects and sample-set effects over seeds, including variance and tail-risk, instead of only the mean.",
        "Defines attribution for stochastic training as the dependence of an output distribution on the training dataset and evaluates distribution-aware pruning.",
        "The demonstrated pruning tasks do not establish the number of seeds needed for Stage1's constrained operating frontier.",
        "SUPPORTS",
        "Training on one dataset yields a distribution of models, so attribution should target output distributions.",
    ),
    DeepPaper(
        "DEEP_BENCHMARK_VARIANCE_2021",
        "Accounting for Variance in Machine Learning Benchmarks",
        "Xavier Bouthillier; Pierre Delaunay; Mirko Bronzi; Assya Trofimov; et al.",
        2021,
        "MLSys 2021",
        "https://proceedings.mlsys.org/paper_files/paper/2021/hash/0184b0cd3cfb185989f858a1d9f5c1eb-Abstract.html",
        "",
        "EXPERIMENTAL_VARIANCE",
        "D1_CONDITIONAL_VALUE",
        "variance-aware benchmarking",
        "variation from data sampling, augmentation, initialization, and hyperparameters",
        "training pipeline comparison",
        "YES_ACROSS_RUNS",
        "AT_ARM_LEVEL",
        "paired_seeds;selection_identity;machine_and_config_provenance",
        "DIRECT_FOR_CAMPAIGN_DESIGN",
        "Use paired seeds and report uncertainty over six-arm effects; a best run is not evidence of a reliable policy.",
        "Models the complete benchmark process and compares estimators that include multiple sources of experimental variation.",
        "Its benchmark error analysis is general and does not specify Stage1's operational success criterion.",
        "SUPPORTS",
        "Data sampling, initialization, augmentation, and hyperparameter choices materially affect benchmark conclusions.",
    ),
    DeepPaper(
        "DEEP_UNDERSPECIFICATION_2022",
        "Underspecification Presents Challenges for Credibility in Modern Machine Learning",
        "Alexander D'Amour; Katherine Heller; Dan Moldovan; Ben Adlam; et al.",
        2022,
        "JMLR",
        "https://jmlr.org/papers/v23/20-1335.html",
        "",
        "EXPERIMENTAL_VARIANCE",
        "D1_CONDITIONAL_VALUE",
        "underspecification stress testing",
        "behavioral variation among equally valid predictors",
        "trained model across seeds and deployment slices",
        "YES_ACROSS_RUNS",
        "AT_MODEL_AND_SLICE_LEVEL",
        "paired_seeds;raw_predictions;deployment_slices;blind_holdout",
        "DIRECT_FOR_INTERPRETATION",
        "Treat models with similar aggregate metrics as non-equivalent until the protected tails agree.",
        "Shows that pipelines can return many predictors with similar in-domain performance but materially different deployment behavior.",
        "It diagnoses a broad credibility failure mode rather than a sample-selection algorithm.",
        "SUPPORTS",
        "Equivalent headline performance can hide large behavioral differences across valid trained models.",
    ),
    DeepPaper(
        "DEEP_MEMORIZATION_2017",
        "A Closer Look at Memorization in Deep Networks",
        "Devansh Arpit; Stanislaw Jastrzebski; Nicolas Ballas; David Krueger; et al.",
        2017,
        "ICML 2017",
        "https://proceedings.mlr.press/v70/arpit17a.html",
        "",
        "TRAINING_DYNAMICS",
        "D1_CONDITIONAL_VALUE",
        "memorization dynamics",
        "learning order for simple patterns, real data, and noise",
        "sample population over training",
        "YES",
        "NO",
        "per_sample_loss_or_margin_trajectory;epoch;label_quality_review",
        "DIRECT_FOR_DIAGNOSIS",
        "Separate early learnability from late memorization before calling persistent hard samples valuable.",
        "Contrasts optimization on real and noise data and finds that deep networks tend to learn simple patterns before memorizing noise.",
        "Population-level memorization behavior does not identify whether replaying one Stage1 sample helps the protected tail.",
        "CAUTIONS",
        "Deep networks can eventually fit noise, while learning simpler regularities earlier.",
    ),
    DeepPaper(
        "DEEP_FORGETTING_2019",
        "An Empirical Study of Example Forgetting during Deep Neural Network Learning",
        "Mariya Toneva; Alessandro Sordoni; Remi Tachet des Combes; Adam Trischler; Yoshua Bengio; Geoffrey J. Gordon",
        2019,
        "ICLR 2019",
        "https://openreview.net/forum?id=BJlxm30cKm",
        "",
        "TRAINING_DYNAMICS",
        "D1_CONDITIONAL_VALUE",
        "example forgetting",
        "correct-to-incorrect transitions over epochs",
        "sample",
        "YES",
        "NO_OR_PARTIAL",
        "per_sample_correctness_trajectory;epoch;label",
        "DIRECT_FOR_OOF_DIAGNOSIS",
        "Use forgetting as a reproducible sample descriptor and test its interaction with seed, not as a final value label.",
        "Counts forgetting events from correctness transitions and studies the effect of removing unforgettable examples.",
        "Forgetting depends on model and training recipe and does not encode the direction of an operational-tail update.",
        "CAUTIONS",
        "Samples differ in how often they are learned and later forgotten during training.",
    ),
    DeepPaper(
        "DEEP_DATASET_CARTOGRAPHY_2020",
        "Dataset Cartography: Mapping and Diagnosing Datasets with Training Dynamics",
        "Swabha Swayamdipta; Roy Schwartz; Nicholas Lourie; Yizhong Wang; Hannaneh Hajishirzi; Noah A. Smith; Yejin Choi",
        2020,
        "EMNLP 2020",
        "https://aclanthology.org/2020.emnlp-main.746/",
        "10.18653/v1/2020.emnlp-main.746",
        "TRAINING_DYNAMICS",
        "D1_CONDITIONAL_VALUE",
        "dataset cartography",
        "mean true-class confidence and variability over epochs",
        "sample",
        "YES",
        "NO_OR_PARTIAL",
        "per_sample_probability_trajectory;label;epoch",
        "DIRECT_FOR_OOF_DIAGNOSIS",
        "Define easy, ambiguous, and hard-to-learn strata descriptively, then test replay effects within each stratum.",
        "Builds data maps from per-example confidence and variability and compares subsets across in-domain and out-of-domain tests.",
        "The original NLP buckets are model-relative and should not be treated as universal Stage1 value classes.",
        "CAUTIONS",
        "Training trajectories reveal easy, ambiguous, and hard-to-learn regions with different roles.",
    ),
    DeepPaper(
        "DEEP_RHO_LOSS_2022",
        "Prioritized Training on Points that are Learnable, Worth Learning, and not yet Learnt",
        "Soren Mindermann; Jan M. Brauner; Muhammed T. Razzak; Mrinank Sharma; et al.",
        2022,
        "ICML 2022",
        "https://proceedings.mlr.press/v162/mindermann22a.html",
        "",
        "TRAINING_DYNAMICS",
        "D1_CONDITIONAL_VALUE",
        "reducible holdout loss selection",
        "current loss minus irreducible holdout loss",
        "sample at a training step",
        "YES",
        "PARTIAL_FOR_GENERALIZATION",
        "online_sample_loss;independent_holdout_loss_model;training_step",
        "PILOT_REQUIRES_NEW_MODEL",
        "Test reducible loss only in a bounded pilot; existing OOF probabilities do not reconstruct the independent irreducible-loss model.",
        "Selects examples estimated to reduce generalization loss by discounting points that are hard because they are noisy or unlearnable.",
        "Its objective is average holdout loss, not the asymmetric Stage1 weak-defect and difficult-normal frontier.",
        "SUPPORTS",
        "Raw high loss conflates useful learnable points with noisy or unlearnable points.",
    ),
    DeepPaper(
        "DEEP_REPLAY_SCHEDULING_2022",
        "Learn the Time to Learn: Replay Scheduling in Continual Learning",
        "Marcus Klasson; Hedvig Kjellstrom; Cheng Zhang",
        2022,
        "arXiv",
        "https://arxiv.org/abs/2209.08660",
        "",
        "DYNAMIC_REPLAY",
        "D2_DYNAMIC_REPLAY",
        "learned replay scheduling",
        "which prior tasks are replayed at each training time",
        "task replay allocation over time",
        "YES",
        "AT_SCHEDULE_LEVEL",
        "epoch;replay_role;configured_weight;realized_exposure;validation_outcome",
        "DIRECT_FOR_SCHEDULE_ABLATION",
        "Hold selection fixed and compare continuous replay with preregistered decay and stop schedules.",
        "Uses search and reinforcement learning to choose replay schedules and compares them with equal replay policies.",
        "Continual task replay differs from same-task sample replay, so only the timing hypothesis transfers directly.",
        "SUPPORTS",
        "When replay occurs can matter even when stored data and total processing constraints are fixed.",
    ),
    DeepPaper(
        "DEEP_EXPERIENCE_REPLAY_2019",
        "Experience Replay for Continual Learning",
        "David Rolnick; Arun Ahuja; Jonathan Schwarz; Timothy Lillicrap; Gregory Wayne",
        2019,
        "NeurIPS 2019",
        "https://proceedings.neurips.cc/paper_files/paper/2019/hash/fa7cdfad1a5aaf8370ebeda47a1ff1c3-Abstract.html",
        "",
        "DYNAMIC_REPLAY",
        "D2_DYNAMIC_REPLAY",
        "experience replay with stability-plasticity controls",
        "performance and forgetting under replay mixtures",
        "replay buffer and current experience",
        "YES",
        "AT_BEHAVIOR_LEVEL",
        "replay_fraction;current_fraction;stored_targets;per_epoch_outcomes",
        "CONTEXT_FOR_REPLAY_CONTROL",
        "Track the replay/base mixture explicitly and protect old behavior instead of assuming more replay is always safer.",
        "Combines current and replayed experience with behavioral cloning to balance plasticity and stability.",
        "The experiments are multi-task reinforcement learning rather than supervised industrial inspection.",
        "CONTEXT",
        "Replay trades off acquisition of new behavior against preservation of prior behavior.",
    ),
    DeepPaper(
        "DEEP_MAX_INTERFERED_REPLAY_2019",
        "Online Continual Learning with Maximal Interfered Retrieval",
        "Rahaf Aljundi; Eugene Belilovsky; Tinne Tuytelaars; Laurent Charlin; Massimo Caccia; Min Lin; Lucas Page-Caccia",
        2019,
        "NeurIPS 2019",
        "https://proceedings.neurips.cc/paper_files/paper/2019/hash/15825aee15eb335cc13f9b559f166ee8-Abstract.html",
        "",
        "DYNAMIC_REPLAY",
        "D2_DYNAMIC_REPLAY",
        "interference-aware replay retrieval",
        "predicted loss increase after a prospective update",
        "replay sample conditional on current update",
        "YES_PER_STEP",
        "YES_FOR_INTERFERENCE",
        "candidate_gradients_or_virtual_update;memory_predictions;training_step",
        "BOUNDED_GRADIENT_PILOT",
        "Measure whether difficult-normal replay is predicted to damage weak-defect probes at key checkpoints.",
        "Retrieves memories whose predictions would be most negatively affected by the prospective parameter update.",
        "Preventing forgetting in task streams is not equivalent to maximizing Stage1 TN under an FN constraint.",
        "SUPPORTS",
        "Replay value can be conditional on the current model update and interference with protected examples.",
    ),
    DeepPaper(
        "DEEP_AUM_2020",
        "Identifying Mislabeled Data using the Area Under the Margin Ranking",
        "Geoff Pleiss; Tianyi Zhang; Ethan Elenberg; Kilian Q. Weinberger",
        2020,
        "NeurIPS 2020",
        "https://proceedings.neurips.cc/paper_files/paper/2020/hash/c6102b3727b2a7d8b1bb6981147081ef-Abstract.html",
        "",
        "NOISY_LABELS",
        "D3_WEAK_DEFECT_GUARD",
        "area under the margin",
        "assigned-class logit margin integrated over training",
        "sample",
        "YES",
        "PARTIAL_FOR_NOISE",
        "per_sample_logits_or_binary_margin;epoch;label",
        "DIRECT_BINARY_APPROXIMATION",
        "Use margin trajectories to quarantine noise-like replay candidates, while retaining a separate protected weak-defect probe.",
        "Uses the average training-time margin and synthetic threshold samples to identify likely mislabeled data.",
        "Low margin also includes valid ambiguous or hard-clean examples; AUM is not a direct replay-benefit estimator.",
        "CAUTIONS",
        "Training-time margins can separate many mislabeled examples from clean data but do not perfectly identify hard-clean cases.",
    ),
    DeepPaper(
        "DEEP_COTEACHING_2018",
        "Co-teaching: Robust training of deep neural networks with extremely noisy labels",
        "Bo Han; Quanming Yao; Xingrui Yu; Gang Niu; Miao Xu; Weihua Hu; Ivor Tsang; Masashi Sugiyama",
        2018,
        "NeurIPS 2018",
        "https://proceedings.neurips.cc/paper_files/paper/2018/hash/a19744e268754fb0148b017647355b7b-Abstract.html",
        "",
        "NOISY_LABELS",
        "D3_WEAK_DEFECT_GUARD",
        "peer small-loss sample selection",
        "small-loss selection exchanged between two networks",
        "mini-batch sample",
        "YES",
        "PARTIAL_FOR_LABEL_NOISE",
        "two_model_losses;selection_exchange;noise_rate_schedule",
        "FUTURE_ONLY_NOT_DEFAULT",
        "Use its clean-first caution to interpret extreme hard samples; do not add two-network training to the first campaign.",
        "Two networks exchange their small-loss examples so each updates from the peer's selected data rather than its own errors.",
        "Small loss can favor easy samples and the assumed noise-rate schedule is unavailable in Stage1.",
        "CAUTIONS",
        "Very hard examples may be label noise that deep networks memorize late in training.",
    ),
    DeepPaper(
        "DEEP_CODIS_2023",
        "Combating Noisy Labels with Sample Selection by Mining High-Discrepancy Examples",
        "Xiaobo Xia; Bo Han; Yibing Zhan; Jun Yu; Mingming Gong; Chen Gong; Tongliang Liu",
        2023,
        "ICCV 2023",
        "https://openaccess.thecvf.com/content/ICCV2023/html/Xia_Combating_Noisy_Labels_with_Sample_Selection_by_Mining_High-Discrepancy_Examples_ICCV_2023_paper.html",
        "",
        "NOISY_LABELS",
        "D3_WEAK_DEFECT_GUARD",
        "high-discrepancy clean-sample mining",
        "prediction-probability discrepancy between two networks",
        "sample",
        "YES",
        "PARTIAL_FOR_HARD_CLEAN",
        "two_model_probability_trajectories;labels;sample_selection",
        "FUTURE_OR_SMALL_PILOT",
        "Distinguish persistent hard-clean candidates from consensus errors before increasing replay dose.",
        "Maintains two-network divergence by selecting likely-clean examples with high probability discrepancy, admitting more hard-clean samples than disagreement-only rules.",
        "Requires two networks and noisy-label assumptions; discrepancy does not prove a positive Stage1 tail effect.",
        "SUPPORTS",
        "Hard-clean samples and noisy samples require more than a single loss or confidence threshold to separate.",
    ),
    DeepPaper(
        "DEEP_INFLUENCE_FUNCTIONS_2017",
        "Understanding Black-box Predictions via Influence Functions",
        "Pang Wei Koh; Percy Liang",
        2017,
        "ICML 2017",
        "https://proceedings.mlr.press/v70/koh17a.html",
        "",
        "DATA_ATTRIBUTION",
        "D4_GRADIENT_PILOT",
        "influence functions",
        "first-order effect of upweighting a training point on a target loss",
        "training-target sample pair",
        "POST_CONVERGENCE_LOCAL",
        "YES_FOR_TARGET_LOSS",
        "per_sample_gradient;target_gradient;inverse_hessian_vector_product",
        "BOUNDED_PILOT_ONLY",
        "Use the target-loss formulation, but avoid claiming exact influence without Hessian and convergence checks.",
        "Approximates the effect of infinitesimal training-point upweighting using gradients and inverse-Hessian-vector products.",
        "Classical assumptions fail for non-convex, non-converged deep training and large finite replay weights.",
        "CONTEXT",
        "Influence must be defined relative to a target behavior, not by gradient magnitude alone.",
    ),
    DeepPaper(
        "DEEP_TRACIN_2020",
        "Estimating Training Data Influence by Tracing Gradient Descent",
        "Garima Pruthi; Frederick Liu; Satyen Kale; Mukund Sundararajan",
        2020,
        "NeurIPS 2020",
        "https://proceedings.neurips.cc/paper/2020/hash/e6385d39ec9394f2f3a354d9d2b88eec-Abstract.html",
        "",
        "DATA_ATTRIBUTION",
        "D4_GRADIENT_PILOT",
        "checkpoint gradient tracing",
        "learning-rate-weighted gradient dot products across checkpoints",
        "training-target sample pair over checkpoints",
        "YES",
        "YES_FOR_TARGET_LOSS",
        "key_checkpoints;per_sample_gradients;learning_rate;target_probe_gradients",
        "DIRECT_BOUNDED_PILOT",
        "Collect last-layer gradient alignment at 120, 140, 150, 160, 180, and 200 for candidates and fixed tail probes.",
        "Approximates training-point influence by accumulating target-training gradient similarity at saved checkpoints.",
        "Checkpoint and layer subsampling are approximations and can miss path effects outside the measured layers or times.",
        "SUPPORTS",
        "Influence can change over the training path and is not captured by a final checkpoint alone.",
    ),
    DeepPaper(
        "DEEP_TRAK_2023",
        "TRAK: Attributing Model Behavior at Scale",
        "Sung Min Park; Kristian Georgiev; Andrew Ilyas; Guillaume Leclerc; Aleksander Madry",
        2023,
        "ICML 2023",
        "https://proceedings.mlr.press/v202/park23c.html",
        "",
        "DATA_ATTRIBUTION",
        "D4_GRADIENT_PILOT",
        "randomly projected after-kernel attribution",
        "projected gradient features aggregated over trained models",
        "training-target sample pair across models",
        "YES_ACROSS_MODELS",
        "YES_FOR_TARGET_OUTPUT",
        "multiple_models;projected_gradients;target_outputs",
        "PILOT_AFTER_LAST_LAYER_BASELINE",
        "Reserve TRAK for escalation if last-layer alignment is reproducible and informative across seeds.",
        "Uses random projection and a small ensemble of trained models to scale predictive data attribution.",
        "It remains substantially heavier than the first last-layer pilot and does not remove stochastic attribution uncertainty.",
        "CONTEXT",
        "Scalable attribution still requires multiple models and a precisely specified target behavior.",
    ),
    DeepPaper(
        "DEEP_SOURCE_2024",
        "Training Data Attribution via Approximate Unrolling",
        "Juhan Bae; Wu Lin; Jonathan Lorraine; Roger Grosse",
        2024,
        "NeurIPS 2024",
        "https://proceedings.neurips.cc/paper_files/paper/2024/hash/7af60ccb99c7a434a0d9d9c1fb00ca94-Abstract-Conference.html",
        "10.52202/079017-2129",
        "DATA_ATTRIBUTION",
        "D4_GRADIENT_PILOT",
        "approximate unrolled differentiation",
        "counterfactual effect through non-converged or multi-stage optimization",
        "training subset on target behavior",
        "YES",
        "YES_FOR_TARGET_OUTPUT",
        "checkpoints;optimizer_state;training_stage_boundaries;target_outputs",
        "ESCALATION_ONLY",
        "Preserve optimizer and stage provenance now so a path-aware attribution study remains possible after the campaign.",
        "Connects implicit differentiation and unrolling to handle non-converged models and multi-stage training more faithfully.",
        "Approximate unrolling remains costly and is not justified before the bounded gradient pilot shows signal.",
        "SUPPORTS",
        "Non-convergence and multi-stage training can invalidate endpoint-only attribution approximations.",
    ),
    DeepPaper(
        "DEEP_OGA_2025",
        "Outlier Gradient Analysis: Efficiently Identifying Detrimental Training Samples for Deep Learning Models",
        "Anshuman Chhabra; Bo Li; Jian Chen; Prasant Mohapatra; Hongfu Liu",
        2025,
        "ICML 2025",
        "https://proceedings.mlr.press/v267/chhabra25a.html",
        "",
        "DATA_ATTRIBUTION",
        "D4_GRADIENT_PILOT",
        "outlier gradient analysis",
        "gradient outlierness linked to detrimental influence",
        "sample gradient",
        "CHECKPOINT_DEPENDENT",
        "YES_FOR_DETRIMENTAL_CANDIDATES",
        "per_sample_gradient_embedding;robust_outlier_reference;target_outcomes",
        "DIRECT_BOUNDED_PILOT",
        "Add gradient outlier status as a risk flag, not a positive-value score, in the key-checkpoint pilot.",
        "Reformulates detrimental-sample identification as Hessian-free gradient outlier detection and evaluates noise detection and data selection.",
        "Gradient outlierness is model- and representation-dependent and may also flag rare but valid Stage1 modes.",
        "SUPPORTS",
        "Large or unusual gradients can indicate harmful samples rather than useful difficulty.",
    ),
    DeepPaper(
        "DEEP_GRADMATCH_2021",
        "GRAD-MATCH: Gradient Matching based Data Subset Selection for Efficient Deep Model Training",
        "Krishnateja Killamsetty; Durga S.; Ganesh Ramakrishnan; Abir De; Rishabh Iyer",
        2021,
        "ICML 2021",
        "https://proceedings.mlr.press/v139/killamsetty21a.html",
        "",
        "DATA_SUBSET_SELECTION",
        "D4_GRADIENT_PILOT",
        "aggregate gradient matching",
        "distance between subset and training or validation gradient",
        "weighted subset",
        "YES_ONLINE_VARIANT",
        "YES_RELATIVE_TO_REFERENCE_GRADIENT",
        "candidate_gradient_embeddings;target_gradient;subset_weights",
        "DIRECT_BOUNDED_PILOT",
        "Compare aggregate selected-set gradient with separate difficult-normal and weak-defect target gradients.",
        "Uses orthogonal matching pursuit to choose a weighted subset whose gradient matches a training or validation reference gradient.",
        "Matching one aggregate validation gradient can hide conflict between the two protected Stage1 tails.",
        "SUPPORTS",
        "Gradient direction and aggregate subset coverage matter beyond individual gradient norm.",
    ),
    DeepPaper(
        "DEEP_DATA_DIET_2021",
        "Deep Learning on a Data Diet: Finding Important Examples Early in Training",
        "Mansheej Paul; Surya Ganguli; Gintare Karolina Dziugaite",
        2021,
        "NeurIPS 2021",
        "https://proceedings.neurips.cc/paper/2021/hash/ac56f8fe9eea3e4a365f29f0f1957c55-Abstract.html",
        "",
        "STATIC_SCORE_BASELINES",
        "D8_STATIC_SCORE_BASELINES",
        "GraNd and EL2N early-training scores",
        "expected gradient norm and error-vector norm",
        "sample averaged over initializations",
        "EARLY_TRAINING",
        "NO",
        "early_per_sample_gradients_or_probabilities;multiple_initializations",
        "EL2N_DIRECT_GRAND_PILOT",
        "Keep EL2N and GraNd as preregistered baselines; require paired-seed operational validation before promotion.",
        "Scores examples early using expected gradient norm or prediction-error norm and evaluates data pruning across architectures.",
        "Importance for pruning average accuracy is not equivalent to beneficial replay at an FN-constrained operating point.",
        "CAUTIONS",
        "Early gradient or error magnitude can identify important examples, but the score does not encode target-direction benefit.",
    ),
    DeepPaper(
        "DEEP_SGD_STABILITY_2016",
        "Train faster, generalize better: Stability of stochastic gradient descent",
        "Moritz Hardt; Ben Recht; Yoram Singer",
        2016,
        "ICML 2016",
        "https://proceedings.mlr.press/v48/hardt16.html",
        "",
        "OPTIMIZATION_STABILITY",
        "D5_REALIZED_EXPOSURE",
        "algorithmic stability of stochastic gradient methods",
        "parameter and generalization sensitivity to one-example dataset changes",
        "training algorithm and exposure sequence",
        "YES",
        "AT_ALGORITHM_LEVEL",
        "optimizer_steps;learning_rate;sample_exposure_order;paired_dataset_runs",
        "DIRECT_FOR_TELEMETRY",
        "Record realized exposure and optimizer steps; identical configured replay weight need not imply identical optimization impact.",
        "Bounds and empirically probes how SGD sensitivity depends on step count, learning rate, and when a changed example is encountered.",
        "The smoothness assumptions and simple experimental models do not hold exactly for YOLO training.",
        "CONTEXT",
        "The timing and number of stochastic updates affect stability and generalization sensitivity.",
    ),
    DeepPaper(
        "DEEP_INFOBATCH_2024",
        "InfoBatch: Lossless Training Speed Up by Unbiased Dynamic Data Pruning",
        "Ziheng Qin; Kai Wang; Zangwei Zheng; Jianyang Gu; Xiangyu Peng; et al.",
        2024,
        "ICLR 2024",
        "https://openreview.net/forum?id=C61sk5LsK6",
        "",
        "OPTIMIZATION_STABILITY",
        "D5_REALIZED_EXPOSURE",
        "unbiased dynamic data pruning",
        "loss-based retention probability and rescaled gradient contribution",
        "sample at each training stage",
        "YES",
        "NO_FOR_TARGET_VALUE",
        "per_sample_loss;retention_probability;realized_selection;loss_scale",
        "DIRECT_TELEMETRY_ANALOGY",
        "Log configured and realized replay inclusion plus effective loss scaling, not only manifest membership.",
        "Randomly prunes lower-loss samples and rescales retained contributions to reduce gradient-expectation bias.",
        "Preserving the full-data expected gradient is a different objective from improving Stage1's asymmetric tail frontier.",
        "SUPPORTS",
        "Dynamic sample inclusion changes gradient expectation unless realized sampling and correction are controlled.",
    ),
    DeepPaper(
        "DEEP_D2_PRUNING_2024",
        "D2 Pruning: Message Passing for Balancing Diversity and Difficulty in Data Pruning",
        "Adyasha Maharana; Prateek Yadav; Mohit Bansal",
        2024,
        "ICLR 2024",
        "https://openreview.net/forum?id=thbtoAkCe9",
        "",
        "DATA_SUBSET_SELECTION",
        "D6_DIVERSITY_COVERAGE",
        "graph message passing for diversity and difficulty",
        "difficulty propagated over a sample-similarity graph",
        "subset",
        "SELECTION_STAGE",
        "NO",
        "sample_embedding;difficulty_score;similarity_graph;selection_budget",
        "DIRECT_FOR_SELECTION_CONSTRAINT",
        "Apply video limits and embedding-space coverage after defining a candidate mechanism signal.",
        "Uses forward and reverse graph message passing to combine difficulty with coverage of neighboring sample regions.",
        "Diversity can reduce redundancy but cannot make a target-opposed gradient beneficial.",
        "SUPPORTS",
        "Difficulty-only and diversity-only subsets have complementary failure modes.",
    ),
    DeepPaper(
        "DEEP_INFOMAX_PRUNING_2025",
        "Data Pruning by Information Maximization",
        "Haoru Tan; Sitong Wu; Wei Huang; Shizhen Zhao; Xiaojuan Qi",
        2025,
        "ICLR 2025",
        "https://arxiv.org/abs/2506.01701",
        "",
        "DATA_SUBSET_SELECTION",
        "D6_DIVERSITY_COVERAGE",
        "importance-minus-redundancy optimization",
        "sample importance and pairwise similarity penalty",
        "subset",
        "SELECTION_STAGE",
        "NO",
        "importance_score;pairwise_similarity;selection_budget",
        "DIRECT_FOR_SELECTION_CONSTRAINT",
        "Use a transparent coverage optimizer within each preregistered candidate stratum rather than an arbitrary blended score.",
        "Frames coreset selection as discrete quadratic optimization of total importance minus pairwise redundancy.",
        "The method assumes the supplied importance score is meaningful; it does not solve Stage1's conditional-value problem.",
        "SUPPORTS",
        "Redundant high-score samples can add less information than a diverse lower-ranked subset.",
    ),
    DeepPaper(
        "DEEP_MODERATE_CORESET_2023",
        "Moderate Coreset: A Universal Method of Data Selection for Real-world Data-efficient Deep Learning",
        "Xiaobo Xia; Jiale Liu; Jun Yu; Xu Shen; Bo Han; Tongliang Liu",
        2023,
        "ICLR 2023",
        "https://openreview.net/forum?id=7D5EECbOaf9",
        "",
        "DATA_SUBSET_SELECTION",
        "D6_DIVERSITY_COVERAGE",
        "moderate-score coreset",
        "distance of a score from its class median",
        "sample subset",
        "SELECTION_STAGE",
        "NO",
        "class_conditional_score_distribution;sample_embedding;budget",
        "DIRECT_STATIC_BASELINE",
        "Include moderate-band controls so extreme hardest-tail replay is not the only non-random comparator.",
        "Selects samples near the class-conditional score median as a scenario-robust proxy for the full distribution.",
        "Median proximity is a robust baseline, not evidence of positive operational-tail influence.",
        "CAUTIONS",
        "The optimal score interval changes by scenario; selecting an extreme score tail is not universally robust.",
    ),
    DeepPaper(
        "DEEP_DATASET_PRUNING_2023",
        "Dataset Pruning: Reducing Training Data by Examining Generalization Influence",
        "Shuo Yang; Zeke Xie; Hanyu Peng; Min Xu; Mingming Sun; Ping Li",
        2023,
        "ICLR 2023",
        "https://openreview.net/forum?id=4wZiAXD29TQ",
        "",
        "DATA_SUBSET_SELECTION",
        "D6_DIVERSITY_COVERAGE",
        "generalization-influence subset optimization",
        "estimated generalization gap after subset removal",
        "subset",
        "SELECTION_AND_TRAINING",
        "YES_FOR_GENERALIZATION_GAP",
        "subset_scores;validation_loss;training_configuration",
        "METHOD_LEVEL_COMPARATOR",
        "Evaluate sample sets, not only isolated ranks, because opposite gradients and interactions can cancel or reinforce.",
        "Optimizes a proxy subset under a constrained generalization gap and analyzes set-level removal influence.",
        "Its average generalization objective does not directly encode the Stage1 FN-constrained raw frontier.",
        "SUPPORTS",
        "Generalization contribution is a property of a selected set and its interactions, not only individual score order.",
    ),
    DeepPaper(
        "DEEP_GLISTER_2021",
        "GLISTER: Generalization based Data Subset Selection for Efficient and Robust Learning",
        "Krishnateja Killamsetty; Durga Sivasubramanian; Ganesh Ramakrishnan; Rishabh Iyer",
        2021,
        "AAAI 2021",
        "https://ojs.aaai.org/index.php/AAAI/article/view/16988",
        "10.1609/aaai.v35i9.16988",
        "DATA_SUBSET_SELECTION",
        "D6_DIVERSITY_COVERAGE",
        "validation-targeted bilevel subset selection",
        "validation likelihood under a selected training subset",
        "subset",
        "YES_ONLINE_VARIANT",
        "YES_FOR_VALIDATION_OBJECTIVE",
        "candidate_losses_or_gradients;heldout_target;subset_budget",
        "BOUNDED_PILOT_OR_COMPARATOR",
        "If gradient selection escalates, define separate difficult-normal and weak-defect held-out targets rather than one average validation loss.",
        "Formulates subset selection as bilevel optimization of held-out likelihood and provides an iterative online approximation.",
        "A single held-out objective can obscure conflict between false-positive reduction and defect-tail preservation.",
        "SUPPORTS",
        "Training subset value should be evaluated against a held-out target objective.",
    ),
    DeepPaper(
        "DEEP_DSDM_2024",
        "DsDm: Model-Aware Dataset Selection with Datamodels",
        "Logan Engstrom; Axel Feldmann; Aleksander Madry",
        2024,
        "ICML 2024",
        "https://proceedings.mlr.press/v235/engstrom24a.html",
        "",
        "DATA_SUBSET_SELECTION",
        "D6_DIVERSITY_COVERAGE",
        "target-aware dataset selection with datamodels",
        "predicted target performance as a function of subset membership",
        "dataset subset",
        "ACROSS_TRAINING_RUNS",
        "YES_FOR_SPECIFIED_TARGET",
        "many_subset_runs;selection_membership;target_task_outcomes",
        "CONCEPTUAL_MATCH_COMPUTE_HEAVY",
        "Use the existing 240 runs as set-level evidence, but require new randomized subset coverage before fitting a Stage1 datamodel.",
        "Optimizes dataset selection for explicit target tasks by modeling how training-set membership changes downstream performance.",
        "Datamodels require broad randomized subset variation; the current fixed method-budget design is not sufficient for causal per-sample coefficients.",
        "SUPPORTS",
        "Human notions of clean or high-quality data can underperform direct model- and target-aware selection.",
    ),
    DeepPaper(
        "DEEP_BADGE_2020",
        "Deep Batch Active Learning by Diverse, Uncertain Gradient Lower Bounds",
        "Jordan T. Ash; Chicheng Zhang; Akshay Krishnamurthy; John Langford; Alekh Agarwal",
        2020,
        "ICLR 2020",
        "https://openreview.net/forum?id=ryghZJBKPS",
        "",
        "ACTIVE_LEARNING",
        "D6_DIVERSITY_COVERAGE",
        "diverse gradient embeddings",
        "hallucinated gradient magnitude and distance",
        "unlabeled query batch",
        "CURRENT_MODEL",
        "NO_FOR_REPLAY_VALUE",
        "last_layer_gradient_embedding;candidate_predictions;budget",
        "DIRECT_DIVERSITY_BASELINE",
        "Use last-layer gradient embeddings for diversity only after positive target alignment is checked.",
        "Uses k-means++ style sampling in hallucinated gradient space to combine uncertainty and batch diversity without a tuned blend weight.",
        "Active-label informativeness is not the same as replay benefit for already labeled samples.",
        "CONTEXT",
        "High uncertainty alone can produce redundant batches; gradient-space diversity addresses coverage.",
    ),
    DeepPaper(
        "DEEP_NP_LEARNING_2005",
        "A Neyman-Pearson Approach to Statistical Learning",
        "Clayton Scott; Robert Nowak",
        2005,
        "IEEE Transactions on Information Theory",
        "https://doi.org/10.1109/TIT.2005.856955",
        "10.1109/TIT.2005.856955",
        "OPERATIONAL_TAIL",
        "D7_OPERATIONAL_TAIL",
        "Neyman-Pearson constrained learning",
        "one error type minimized subject to a bound on the other",
        "classifier and decision threshold",
        "EVALUATION_AND_LEARNING",
        "AT_OUTCOME_LEVEL",
        "raw_predictions;labels;predeclared_error_constraint",
        "DIRECT_FOR_PRIMARY_ENDPOINT",
        "Keep FN at or below the preregistered bound and maximize TN; do not replace the constraint with average accuracy.",
        "Develops statistical learning under an asymmetric error constraint in the Neyman-Pearson style.",
        "Finite-sample guarantees depend on assumptions and do not transfer automatically to the reused Stage1 validation set.",
        "SUPPORTS",
        "Asymmetric deployment objectives require constrained evaluation rather than an unconstrained aggregate metric.",
    ),
    DeepPaper(
        "DEEP_PARTIAL_AUC_2013",
        "A Structural SVM Based Approach for Optimizing Partial AUC",
        "Harikrishna Narasimhan; Shivani Agarwal",
        2013,
        "ICML 2013",
        "https://proceedings.mlr.press/v28/narasimhan13.html",
        "",
        "OPERATIONAL_TAIL",
        "D7_OPERATIONAL_TAIL",
        "partial-AUC optimization",
        "ranking quality in a specified false-positive-rate interval",
        "classifier ranking",
        "TRAINING_AND_EVALUATION",
        "AT_OUTCOME_LEVEL",
        "raw_predictions;labels;predeclared_roc_region",
        "DIRECT_AS_SECONDARY_ENDPOINT",
        "Use the complete raw FN 0-95 frontier and a preregistered partial region to distinguish ranking improvement from threshold movement.",
        "Optimizes a structural surrogate for ROC area restricted to a specified operating interval.",
        "Stage1 will evaluate the raw frontier after training rather than implement the paper's structural SVM objective.",
        "SUPPORTS",
        "Full AUC can hide changes in the narrow deployment-relevant part of the ranking.",
    ),
    DeepPaper(
        "DEEP_CALIBRATION_2017",
        "On Calibration of Modern Neural Networks",
        "Chuan Guo; Geoff Pleiss; Yu Sun; Kilian Q. Weinberger",
        2017,
        "ICML 2017",
        "https://proceedings.mlr.press/v70/guo17a.html",
        "",
        "OPERATIONAL_TAIL",
        "D7_OPERATIONAL_TAIL",
        "post-hoc temperature scaling",
        "agreement between confidence and empirical correctness",
        "trained classifier",
        "POST_TRAINING",
        "NO_FOR_RANKING",
        "raw_logits;calibration_split;labels;calibrated_predictions",
        "DIRECT_DIAGNOSTIC_ONLY",
        "Report raw ranking/frontier separately from calibrated probabilities; calibration must not be called a sample-value gain.",
        "Evaluates calibration failures in modern networks and compares post-processing methods including temperature scaling.",
        "Monotone temperature scaling changes probability interpretation but cannot repair a damaged sample ordering.",
        "CAUTIONS",
        "Calibration and discrimination are different properties and should be evaluated separately.",
    ),
)


def build_deep_read_records() -> list[dict[str, object]]:
    """Return fresh dictionaries so callers cannot mutate the registry."""

    return [_record(paper) for paper in _PAPERS]


__all__ = ["build_deep_read_records"]
