path: ../../datasets/struct6_det_reviewed
train: images/train
val: images/val
test: images/test

names:
  0: CrackBreak
  1: SurfaceDamage
  2: Deformation
  3: JointDislocation
  4: Intrusion
  5: Infiltration
